
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    
  backend:
    container_name: backend
    build: ./core
    expose:
      - "8000"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
      - redis

volumes:
  static_volume:
  media_volume:
  