# Generated by Django 4.2 on 2025-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_reset_token_used",
            field=models.BooleanField(default=False),
        ),
    ]
